### ISSUE TITLE
Keep track of reply count

### ISSUE THREAD

**Issue by johnwarden** [social-protocols/social-network#19]
If we want to show the number or replies next to each post, we should probably store the total in a table somewhere so we don't have to do a SQL count of every post fore very page (related to one of the tasks in #6)

**Comment by fdietze** [comment]
Let's do the naive `select count(*) from ... where postId = ?`. We can optimize that in the future.

**Comment by johnwarden** [comment]
I started doing the select count on very query where we select a post, but this was more work than just adding replies to the postStats table. 

Also we want total replies (all descendants) and not just a count(*)
