### ISSUE TITLE
trivial sign-in for local development

### ISSUE THREAD

**Issue by fdietze** [social-protocols/social-network#4]
Registering a new user every time the database was reset is a lot of manual effort.

Maybe Epic Stack already provides a solution?

**Comment by johnwarden** [comment]
So what I did for myself is, after logging in once, grab my session from the Session table and add it to the seed script.
	await sql`insert into session(id, expirationDate, createdAt, updatedAt, userId) values ('clptz40870001cdvqn4rnggxv', 1704471496999, 1701877981251, 1701877981251, 'clptz40870002cdvq8rqkbfs5')`.execute(
		db,
	)

However, maybe we can create something like a "/dev-login" an endpoint that basically does the same thing.

**Comment by fdietze** [comment]
I just checked their docs. They suggest to create a default user in the seed script. That's also what we do. So just log in with that.
